app.banco=SQL Server Standard 2025

db.url=jdbc:sqlserver://localhost:14330;databaseName=CadastroClientes;integratedSecurity=true;authenticationScheme=NativeAuthentication;encrypt=true;trustServerCertificate=true

db.usuario=
db.senha=