-- Execute conectado como CADASTRO_CLIENTES, o mesmo schema usado pela aplicação.

DECLARE
  tabela_existe NUMBER;
BEGIN
  SELECT COUNT(*) INTO tabela_existe FROM user_tables WHERE table_name = 'USUARIOS';
  IF tabela_existe = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE usuarios (
        id               NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        login            VARCHAR2(50 CHAR) NOT NULL UNIQUE,
        senha            VARCHAR2(255 CHAR) NOT NULL,
        nome             VARCHAR2(100 CHAR) NOT NULL,
        ativo            NUMBER(1) DEFAULT 1 NOT NULL,
        tentativas_falhas NUMBER(1) DEFAULT 0 NOT NULL,
        bloqueado_ate    TIMESTAMP,
        data_criacao     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        data_atualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        CONSTRAINT ck_usuarios_ativo CHECK (ativo IN (0, 1))
      )
    ]';
  END IF;
END;
/

DECLARE
  coluna_existe NUMBER;
BEGIN
  SELECT COUNT(*) INTO coluna_existe FROM user_tab_columns
  WHERE table_name = 'USUARIOS' AND column_name = 'TENTATIVAS_FALHAS';
  IF coluna_existe = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE usuarios ADD (tentativas_falhas NUMBER(1) DEFAULT 0 NOT NULL)';
  END IF;
END;
/

DECLARE
  coluna_existe NUMBER;
BEGIN
  SELECT COUNT(*) INTO coluna_existe FROM user_tab_columns
  WHERE table_name = 'USUARIOS' AND column_name = 'BLOQUEADO_ATE';
  IF coluna_existe = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE usuarios ADD (bloqueado_ate TIMESTAMP)';
  END IF;
END;
/

DECLARE
  indice_existe NUMBER;
BEGIN
  SELECT COUNT(*) INTO indice_existe FROM user_indexes WHERE index_name = 'IDX_USUARIOS_ATIVO';
  IF indice_existe = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX idx_usuarios_ativo ON usuarios(ativo)';
  END IF;
END;
/
-- Exemplo de inserção de usuário padrão (senha: admin123)
-- A senha deve ser gerada com bcrypt cost 12
-- Use a aplicação UsuarioService.criar() para inserir novos usuários
-- INSERT INTO usuarios (login, senha, nome, ativo) 
-- VALUES ('admin', '$2y$12$...', 'Administrador', 1);
