-- Execute este script conectado ao schema Oracle que a aplicacao utilizara.
-- Exemplo para Oracle XE: conecte-se ao servico XEPDB1 como CADASTRO_CLIENTES.

DECLARE
  tabela_existe NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO tabela_existe
    FROM user_tables
   WHERE table_name = 'CLIENTES';

  IF tabela_existe = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE clientes (
        id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nome VARCHAR2(120 CHAR) NOT NULL,
        idade NUMBER(10) NOT NULL,
        cidade VARCHAR2(100 CHAR) NOT NULL,
        email VARCHAR2(160 CHAR) NOT NULL,
        telefone_fixo VARCHAR2(20 CHAR),
        telefone_celular VARCHAR2(20 CHAR),
        CONSTRAINT uq_clientes_email UNIQUE (email)
      )
    ]';
  END IF;
END;
/
